databases:
  - name: face-recogtion-app
    databaseName: face_recogtion_app
    user: face_recogtion_app_user

 services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://face_recogtion_app_user:hUpaBEgEBmJ4pG9XY1O5d8Hlc8H60ZDu@dpg-cfo7s682i3mo4brs6580-a/face_recogtion_app
     fromDatabase:
       name: face_recogtion_app
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50